tradegecko/cinderella

[OLD] tg-compiled-legacy.css/hs_default_custom_styles.css
[OLD] tg-compiled-legacy.css/tg-custom-styles.css

Adding in the lastest changes from hubspot into repo

[REFACTOR] Latest CSS from hubspot

---

styles-legacy/wp-features-list-overview.css
tg-compiled-css/tg-compiled-legacy.css

QA - https://preview.hs-sites.com/_hcms/preview/template/multi?template_layout_id=4500543406&is_buffered_template_layout=true&portalId=407937&tc_deviceCategory=DESKTOP

[NEW CSS] Features List Overview

---

styles-new/lp-google-adwords.css
tg-compiled-css/tg-compiled-new.css

[ENHANCEMENT] Adjusted adwords page margin

---

styles-legacy/blog-popup-modal.css

[FEATURE] Added Blog Modal CSS

---

styles-legacy/blog/jesus-sandals.css
tg-compiled-css/tg-compiled-legacy.css

Same as the previous PR.. Had to redo because of some conflicts..

[ENHANCEMENT] Improved Ryan's Image

---

styles-legacy/1-hs_default_custom_styles.css
styles-legacy/3-tradegecko-styles.css
tg-compiled-css/tg-compiled-legacy.css

[ENHANCEMENT] Fixed search margin-bottom on blog index and post

---

styles-legacy/2-setup-style.css
styles-legacy/3-tradegecko-styles.css
tg-compiled-css/tg-compiled-legacy.css

[ENHANCEMENT] Forms - Quick CSS hygiene update

---

styles-legacy/1-hs_default_custom_styles.css
styles-legacy/2-setup-style.css
styles-legacy/3-tradegecko-styles.css
tg-compiled-css/tg-compiled-legacy.css

1. Margins/Paddings
2. CTA colour
3. Alignments
4. Code cleanups
1. Some of the code - instead of deleting it, I've commented it out because to my knowledge nothing else has been affected - but will be going through the site again and once it's confirmed that nothing else was affected, I'll delete it then =^.^=
**LTR: Before and After** - Desktop
**LTR: Before and After** - Desktop Errors
**LTR: Before and After** - Responsive

[ENHANCEMENT] CSS form update

---

styles-legacy/2-setup-style.css
styles-legacy/3-tradegecko-styles.css
styles-legacy/4-tg-custom-styles.css
tg-compiled-css/tg-compiled-legacy.css

- made the colours consistent with the other forms
- fixed margins/paddings
- also fixed responsive
- modified additional CSS on contact-box.js, but it's not reflected in this repo - so for future references, that file needs to be edited as well if we want to make changes on the contact us form :)
- we might need to revamp the form very soon, but this is just quick fixes to the CSS to make it look more presentable

[ENHANCEMENT] Fixed the contact us form

---

styles-legacy/4-tg-custom-styles.css
styles-legacy/landing-page/addons-b2b.css
styles-legacy/landing-page/addons.css
styles-legacy/landing-page/im-basics.css
tg-compiled-css/tg-compiled-legacy.css

Fixed some pages to make them compatible with the new header.

[BUGFIX] Fixed bugs caused by new header

---

styles-legacy/1-hs_default_custom_styles.css
styles-legacy/3-tradegecko-styles.css
tg-compiled-css/tg-compiled-legacy.css

[ENHANCEMENT] Restyled Basics Side Links

---

styles-legacy/3-tradegecko-styles.css
tg-compiled-css/tg-compiled-legacy.css

- Increased font size
- Updated padding

[ENHANCEMENT] Sidebar update

---

styles-legacy/website-page/sitemap.css
tg-compiled-css/tg-compiled-legacy.css

- switched h2 to h1 for the first title
- updated CSS class names
***BEFORE***
***AFTER***

[ENHANCEMENTS] Updated sitemap h1 tags

---

styles-legacy/4-tg-custom-styles.css
tg-compiled-css/tg-compiled-legacy.css

Fixed the responsive dropdown for the filters 😄

[ENHANCEMENTS] Filters Dropdown Fix

---

styles-legacy/2-setup-style.css
styles-legacy/3-tradegecko-styles.css
styles-legacy/4-tg-custom-styles.css
tg-compiled-css/tg-compiled-legacy.css

- changed the links from green to blue
- updated the blog comments CSS

[ENHANCEMENTS] Links update + Blog Comments CSS update

---

styles-legacy/4-tg-custom-styles.css
styles-legacy/website-page/overview-v2.css
tg-compiled-css/tg-compiled-legacy.css

[ENHANCEMENTS] links update (overview)

---

styles-legacy/blog/popup-modal.css
tg-compiled-css/tg-compiled-legacy.css

[BUGFIX] Fixed blog form popup error and styles

---

styles-legacy/1-hs_default_custom_styles.css
styles-legacy/3-tradegecko-styles.css

- Updated link colours
- Fixed some of the code indentation

[ENHANCEMENT] Update link colours

---

styles-legacy/3-tradegecko-styles.css
styles-legacy/4-tg-custom-styles.css

Updated the CSS for the webinar page - so that it's more in line with the rest of the website's CSS.

[ENHANCEMENTS] Updated Webinar CSS

---

styles-legacy/landing-page/addons-b2b.css

Updated the image URL for the mobile page

[ENHANCEMENTS] Updated the header image for the mobile page

---

styles-new/landing-page/google-adwords.css

[ENHANCEMENTS] New Landing Pages - Form Update

---

styles-new/landing-page/google-adwords.css

[STYLE FIX] More Adwords Tweaks

---

styles-legacy/blog/popup-modal.css

Updated the CSS so that the look of the pop-up is more inline with the rest of the forms:

[ENHANCEMENTS] Blog Pop up Updates

---

styles-legacy/website-page/pricing-v2.css

Marketing CRO test:
- We believe in increasing the contrast of the CTA would lead to more trial signups. 
**BEFORE**
**AFTER**

[ENHANCEMENTS] Pricing Page: Change of CTA colour

---

styles-legacy/blog/blog-sidebar.css

[ENHANCEMENTS] Updated the blog sidebar

---

styles-new/landing-page/google-adwords.css
styles-new/landing-page/webinar.css

[NEW PAGE] Webinar CSS

---

styles-legacy/4-tg-custom-styles.css

[ENHANCEMENTS] Updated header tags in blog posts

---

styles-legacy/4-tg-custom-styles.css

[STYLEFIX] Addons Masthead Spacing

---

styles-legacy/landing-page/addons.css

[STYLEFIX] Addons masthead play button alignment

---

styles-legacy/4-tg-custom-styles.css
styles-legacy/landing-page/addons-b2b.css

[ENHANCEMENT] Tiny Tweaks to LP Masthead

---

styles-legacy/website-page/business-tools.css

[ENHANCEMENT] Add New Tools Tag

---

styles-new/landing-page/google-adwords.css

[ENHANCEMENT] Team Photo Adwords Fix

---

styles-new/landing-page/google-adwords.css

[ENHANCEMENT] Adwords Form Height Fix

---

styles-new/landing-page/google-adwords.css

[ENHANCEMENT] Adwords Form Height

---

styles-new/landing-page/google-adwords.css

[ENHANCEMENT] Extra Adwords Header Images
